values = {
"{{Full Name}}": "Full Name",
"{{Banking App}}": "Bank App",
"{{Account Number}}": "Account Number",
"{{Customer Support Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Customer Support Team}}": "Customer Support Team",
"{{Company Website URL}}": "www.mybank.com",
"{{Customer Support}}": "Customer Support",
"{{Customer Support Email}}": "mybank-customersupport@gmail.com",
"{{Mortgage Account Number}}": "Mortgage Account Number",
"{{Mortgage Account}}": "Mortgage Account",
"{{Name on the Mortgage Account}}":"Name on the Mortgage Account",
"{{Billing}}": "Billing",
"{{Username}}": "Username",
"{{Customer Support Phone Number}}":"+1-234-567-8910",
"{{Live Chat}}": "Live Chat",
"{{Company Website}}": "www.mybank.com",
"{{Mortgage Department}}": "Mortgage Department",
"{{Account}}": "Account",
"{{Name}}": "Name",
"{{Bank Name}}": "Bank Name",
"{{Password}}": "Password",
"{{Customer Support Email Address}}": "mybank-customersupport@gmail.com",
"{{Email Address}}": "Email Address",
"{{Profile}}": "Profile",
"{{Customer Service Working Hours}}": "Customer Service Working Hours",
"{{Credit Card}}": "Credit Card",
"{{Bank App}}": "Bank App",
"{{Loan Account Number}}": "Loan Account Number",
"{{Account Settings}}": "Account Settings",
"{{Payment & Billing}}": "Payment & Billing",
"{{24/7}}": "24/7",
"{{24/7 Customer Support}}": "24/7 Customer Support", 
"{{24/7 Customer Support Hotline}}": "+1-234-567-8910",
"{{24/7 Customer Support Line}}": "+1-234-567-8910",
"{{24/7 Customer Support Number}}": "+1-234-567-8910",
"{{24/7 Customer Support Phone Number}}": "+1-234-567-8910",
"{{24/7 Customer Support Team}}": "24/7 Customer Support Team",
"{{24/7 Live Chat}}": "24/7 Live Chat",
"{{24/7 customer support team}}":"24/7 customer support team",
"{{24/7 helpline}}":"24/7 helpline",
"{{AMEX Customer Service Number}}":"+1-234-567-8910",
"{{AMEX Customer Service Phone Number}}":"+1-234-567-8910",
"{{AMEX Customer Support}}":"AMEX Customer Support",
"{{AMEX Customer Support Phone Number}}":"+1-234-567-8910",
"{{AMEX Customer Support Working Hours}}":"Mon-Fri, 9am to 6pm",
"{{AMEX Website URL}}":"www.americanexpress.com",
"{{AMEX website}}":"www.americanexpress.com",
"{{ATM Address}}": "123 Main St, Springfield, IL 62704",
"{{ATM Finder}}": "ATM Finder",
"{{ATM Finder App}}": "Bank ATM Finder App",
"{{ATM Finder Website}}": "www.mybank.com/atm-finder",
"{{ATM Hunter}}": "ATM Hunter",
"{{ATM Location}}": "123 Main St, Springfield, IL 62704",
"{{ATM Locator}}": "ATM Locator",
"{{ATM Locator App}}": "Bank ATM Locator App",
"{{ATM Locator Website}}": "www.mybank.com/atm-locator",
"{{ATM Locator Website 1}}": "www.mybank.com/atm-locator",
"{{ATM Locator Website 2}}": "www.mybank.com/find-atm",
"{{ATM Locator Website URL}}": "www.mybank.com/atm-locator",
"{{ATM Near Me}}": "Find ATMs Near Me",
"{{ATM Support Phone Number}}": "+1-234-567-8910",
"{{ATM Website URL}}": "www.mybank.com/atm",
"{{Account}}": "Account",
"{{Account Access}}": "Secure Account Access",
"{{Account Activity}}": "Recent Account Activity",
"{{Account Balance}}": "Account Balance",
"{{Account Charges}}": "Account Charges",
"{{Account Closure Processing Time}}": "Account Closure Processing Time",
"{{Account Credentials}}": "Account Credentials",
"{{Account Dashboard}}": "Account Dashboard",
"{{Account Details}}": "Account Details",
"{{Account Email}}": "user@domain.com",
"{{Account ID or Username}}": "Account ID or Username",
"{{Account Holder's Name}}": "Account Holder's Name",
"{{Account Email Address}}": "Account Email Address",
"{{Account Number/IBAN}}": "Account Number/IBAN",
"{{Account Information}}": "Account Information",
"{{Account Holder Name}}": "Account Holder Name",
"{{Account Management}}": "Account Management",
"{{Account Platform}}": "Account Platform",
"{{Account Overview}}": "Account Overview",
"{{Account Recovery}}": "Account Recovery",
"{{Account Security}}": "Account Security",
"{{Account Services}}": "Account Services",
"{{Account Settings}}": "Account Settings",
"{{Account Number}}": "Account Number",
"{{Account Login}}": "Account Login",
"{{Account Name}}": "Account Name",
"{{Account Fees}}": "Account Fees",
"{{Account IDs}}": "Account IDs",
"{{Account PIN}}": "Account PIN",
"{{Account ID}}": "Account ID",
"{{Any specific information or requests related to the cancellation}}": "Any specific information or requests related to the cancellation",

"{{American Express International Customer Service Number}}": "+1-800-528-4800",
"{{American Express Customer Support Working Hours}}": "24/7",
"{{American Express Customer Service Phone Number}}": "+1-800-528-4800",
"{{American Express Lost/Stolen Card Phone Number}}": "+1-800-992-3404",
"{{American Express Customer Support Phone Number}}": "+1-800-528-4800",
"{{American Express Customer Service Number}}": "+1-800-528-4800",
"{{American Express Customer Support Number}}": "+1-800-528-4800",
"{{Activate Card International Usage}}": "Activate Card International Usage",
"{{American Express Customer Support}}": "American Express Customer Support",
"{{American Express Phone Number}}": "+1-800-528-4800",
"{{American Express Website URL}}": "www.americanexpress.com",

"{{Analyze your mortgage terms}}": "Analyze your mortgage terms",
"{{Any Additional Information}}": "Any Additional Information",
"{{Activation Hotline Number}}": "+1-234-567-8910",
"{{Activation Phone Number}}": "+1-234-567-8910",
"{{Account or Customer ID}}": "Account or Customer ID",
"{{Account or Card Number}}": "Account or Card Number",
"{{Account Transactions}}": "Account Transactions",
"{{Account Statements}}": "Account Statements",
"{{Amount Transferred}}": "Amount Transferred",
"{{Apartment Address}}": "Apartment Address",
"{{Annual Fee Amount}}": "Annual Fee Amount",
"{{Account Username}}": "Account Username",
"{{American Express}}": "American Express",
"{{Account Summary}}": "Account Summary",
"{{Activate a Card}}": "Activate a Card",
"{{Activate Card}}": "Activate Card",
"{{Activate Now}}": "Activate Now",
"{{Add new card}}": "Add a New Card",
"{{Account Type}}": "Account Type",
"{{Annual Fees}}": "Annual Fees",
"{{Annual Fee}}": "Annual Fee",
"{{Activate}}": "Activate",
"{{Accounts}}": "Accounts",
"{{Address}}": "Address",
"{{Amount}}": "Amount",
"{{App}}": "App",
"{{App Name}}": "App Name",
"{{App Store}}": "App Store",
"{{App Store Link}}": "https://www.appstore.com/mybank",
"{{App Store URL}}": "https://www.appstore.com/mybank",
"{{App Store/Google Play}}": "App Store or Google Play",
"{{App Store/Google Play Store}}": "App Store or Google Play Store",
"{{App Store/Play Store}}": "App Store or Play Store",
"{{Apple App Store}}": "Apple App Store",
"{{Apple Maps}}": "Apple Maps",
"{{Apply Now}}": "Apply Now",
"{{Attend Mortgage Seminars or Workshops}}": "Attend Mortgage Seminars or Workshops",
"{{Authenticate Your Identity}}": "Authenticate Your Identity",
"{{Authentication Method}}": "Authentication Method",
"{{Authorization Letter}}": "Authorization Letter",
"{{Automated Phone Service Number}}": "+1-234-567-8910",
"{{Automated Phone System Number}}": "+1-234-567-8910",
"{{Automated System Phone Number}}": "+1-234-567-8910",
"{{Automated Telephone Banking Number}}": "+1-234-567-8910",
"{{Availability Hours}}": "Mon-Fri, 9am to 6pm",
"{{Balance}}": "Balance",
"{{Balances}}": "Balances",
"{{Bank}}": "Bank",
"{{Bank A}}": "Bank A",
"{{Bank Account}}": "Bank Account",
"{{Bank Account Details}}": "Bank Account Details",
"{{Bank Account Holder Name}}": "Bank Account Holder Name",
"{{Bank Account Number}}": "Bank Account Number",
"{{Bank App}}": "Bank App",
"{{Bank App Name}}": "Bank App",
"{{Bank B}}": "Bank B",
"{{Bank Branch}}": "Bank Branch",
"{{Bank Branch Location}}": "Bank Branch Location",
"{{Bank Branch Locations}}": "Bank Branch Locations",
"{{Bank Branches}}": "Bank Branches",
"{{Bank Contact Number}}": "+1-234-567-8910",
"{{Bank Customer Service Number}}": "+1-234-567-8910",
"{{Bank Customer Service Phone Number}}": "+1-234-567-8910",
"{{Bank Customer Support}}": "Bank Customer Support",
"{{Bank Customer Support Hours}}": "Mon-Fri, 9am to 6pm",
"{{Bank Customer Support Number}}": "+1-234-567-8910",
"{{Bank Customer Support Phone Number}}": "+1-234-567-8910",
"{{Bank Customer Support Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Bank Helpline Number}}": "+1-234-567-8910",
"{{Bank Hotline}}": "+1-234-567-8910",
"{{Bank Hotline Number}}": "+1-234-567-8910",
"{{Bank Information}}": "Bank Information",
"{{Bank Location}}": "Bank Location",
"{{Bank Mobile App}}": "Bank Mobile App",
"{{Bank Name}}": "Bank Name",
"{{Bank Phone Number}}": "+1-234-567-8910",
"{{Bank Routing Number}}": "Bank Routing Number",
"{{Bank Support}}": "Bank Support",
"{{Bank Transfer}}": "Bank Transfer",
"{{Bank Transfer Reference Number}}": "Bank Transfer Reference Number",
"{{Bank Transfer Step 1}}": "Log in to your account",
"{{Bank Transfer Step 2}}": "Enter beneficiary details",
"{{Bank Transfer Step 3}}": "Confirm and complete the transfer",
"{{Bank Transfer Support Team}}": "Bank Transfer Support Team",
"{{Bank Website}}": "www.mybank.com",
"{{Bank Website URL}}": "www.mybank.com",
"{{Bank Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Bank name}}": "Bank Name",
"{{Bank's}}": "Bank's",
"{{Bank's Customer Service Department}}": "Bank's Customer Service Department",
"{{Bank's Mobile App}}": "Bank's Mobile App",
"{{Bank's Name}}": "Bank's Name",
"{{Bank's Online Banking Portal}}": "Bank's Online Banking Portal",
"{{Bank's Website}}": "www.mybank.com",
"{{Bank's Website URL}}": "www.mybank.com",
"{{Bank-to-Bank Transfer}}": "Bank-to-Bank Transfer",
"{{Bank/Branch Locations}}": "Bank/Branch Locations",
"{{Bank/Branch Name}}": "Bank/Branch Name",
"{{Banking}}": "Banking",
"{{Banking App}}": "Bank App",
"{{Banking App Name}}": "Bank App",
"{{Banking App URL}}": "https://www.appstore.com/mybank",
"{{Banking App or Website}}": "Banking App or Website",
"{{Banking Application}}": "Bank App",
"{{Banking Mobile App}}": "Bank Mobile App",
"{{Banking Platform}}": "Banking Platform",
"{{Banking Platform Website}}": "www.mybank.com",
"{{Banking Portal}}": "Banking Portal",
"{{Banking Website}}": "www.mybank.com",
"{{Banking Website URL}}": "www.mybank.com",
"{{Banks}}": "Banks",
"{{Beneficiary Name}}": "Beneficiary Name",
"{{Bill\"}}": "Bill",
"{{Billing}}": "Billing",
"{{Billing Cycle}}": "Billing Cycle",
"{{Billing Details}}": "Billing Details",
"{{Billing History}}": "Billing History",
"{{Billing Information}}": "Billing Information",
"{{Billing Statements}}": "Billing Statements",
"{{Billing Summary}}": "Billing Summary",
"{{Biometric Authentication}}": "Biometric Authentication",
"{{Block}}": "Block",
"{{Block Card}}": "Block Card",
"{{Blocking Services}}": "Blocking Services",
"{{Branch Location}}": "Branch Location",
"{{Branch Locations}}": "Branch Locations",
"{{Branch Locator}}": "Branch Locator",
"{{Branch Opening Hours}}": "Mon-Fri, 9am to 6pm",
"{{Branch Operating Hours}}": "Mon-Fri, 9am to 6pm",
"{{Branch Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Brief Description}}": "Brief Description",
"{{Business Hours}}": "Mon-Fri, 9am to 6pm",
"{{CVC code}}": "CVC Code",
"{{CVV}}": "CVV",
"{{Cancel}}": "Cancel",
"{{Cancel Account}}": "Cancel Account",
"{{Cancel Card}}": "Cancel Card",
"{{Cancel Loan}}": "Cancel Loan",
"{{Cancel Profile}}": "Cancel Profile",
"{{Cancel Transfer}}": "Cancel Transfer",
"{{Cancellation}}": "Cancellation",
"{{Cancellation Department}}": "Cancellation Department",
"{{Cancellation Department Email Address}}": "cancellation@mybank.com",
"{{Cancellation Department Phone Number}}": "+1-234-567-8910",
"{{Cancellation Department Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Cancellation Email}}": "cancellation@mybank.com",
"{{Cancellation Email Address}}": "cancellation@mybank.com",
"{{Cancellation Form}}": "Cancellation Form",
"{{Cancellation Helpline}}": "+1-234-567-8910",
"{{Cancellation Page}}": "www.mybank.com/cancellation",
"{{Cancellation Phone Number}}": "+1-234-567-8910",
"{{Cancellation Policy}}": "Cancellation Policy",
"{{Cancellation Processing Time}}": "2-3 Business Days",
"{{Cancellation Request Form}}": "Cancellation Request Form",
"{{Card}}": "Card",
"{{Card Accounts}}": "Card Accounts",
"{{Card Activation}}": "Card Activation",
"{{Card Activation App}}": "Bank App",
"{{Card Activation Page}}": "www.mybank.com/card-activation",
"{{Card Activation Phone Number}}": "+1-234-567-8910",
"{{Card Activation Status}}": "Card Activation Status",
"{{Card Activation Website URL}}": "www.mybank.com/card-activation",
"{{Card Annual Fee}}": "Card Annual Fee",
"{{Card Annual Fees}}": "Card Annual Fees",
"{{Card Assistance}}": "Card Assistance",
"{{Card Balance}}": "Card Balance",
"{{Card Balances}}": "Card Balances",
"{{Card Benefits}}": "Card Benefits",
"{{Card Benefits #1}}": "Cashback on purchases",
"{{Card Benefits #2}}": "No annual fee for first year",
"{{Card Benefits #3}}": "Travel insurance coverage",
"{{Card Blocking}}": "Card Blocking",
"{{Card Blocking Phone Number}}": "+1-234-567-8910",
"{{Card Blocking Service}}": "Card Blocking Service",
"{{Card Cancellation}}": "Card Cancellation",
"{{Card Charges}}": "Card Charges",
"{{Card Customer Service Number}}": "+1-234-567-8910",
"{{Card Customer Support}}": "Card Customer Support",
"{{Card Details}}": "Card Details",
"{{Card Fees}}": "Card Fees",
"{{Card Hotline Number}}": "+1-234-567-8910",
"{{Card Hotline Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Card Information}}": "Card Information",
"{{Card Issuer}}": "Card Issuer",
"{{Card Issuer Customer Service Number}}": "+1-234-567-8910",
"{{Card Issuer Phone Number}}": "+1-234-567-8910",
"{{Card Issuer Website}}": "www.mybank.com",
"{{Card Issuing Bank}}": "Card Issuing Bank",
"{{Card Lock}}": "Card Lock",
"{{Card Locking Page URL}}": "www.mybank.com/card-lock",
"{{Card Management}}": "Card Management",
"{{Card Number}}": "Card Number",
"{{Card Pricing}}": "Card Pricing",
"{{Card Profile}}": "Card Profile",
"{{Card Protection Department}}": "Card Protection Department",
"{{Card Protection Phone Number}}": "+1-234-567-8910",
"{{Card Provider}}": "Card Provider",
"{{Card Replacement}}": "Card Replacement",
"{{Card Services}}": "Card Services",
"{{Card Services Phone Number}}": "+1-234-567-8910",
"{{Card Services Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Card Settings}}": "Card Settings",
"{{Card Summary}}": "Card Summary",
"{{Card Support Department}}": "Card Support Department",
"{{Card Support Email Address}}": "cardsupport@mybank.com",
"{{Card Support Phone Number}}": "+1-234-567-8910",
"{{Card Support Team}}": "Card Support Team",
"{{Card Type}}": "Card Type",
"{{Cardholder Name}}": "Cardholder Name",
"{{Cardholder Portal}}": "www.mybank.com/cardholder",
"{{Cards}}": "Cards",
"{{Change Password}}": "Change Password",
"{{Charges}}": "Charges",
"{{Chat Support}}": "Chat Support",
"{{Chat Support Working Hours}}": "24/7",
"{{Check Balance}}": "Check Balance",
"{{Check Fees}}": "Check Fees",
"{{Check Loan Payments}}": "Check Loan Payments",
"{{Check Mortgage Payments}}": "Check Mortgage Payments",
"{{Checking Account}}": "Checking Account",
"{{City}}": "City",
"{{City Name}}": "City Name",
"{{Client Service Email}}": "clientservice@mybank.com",
"{{Client Service Email Address}}": "clientservice@mybank.com",
"{{Client Service Phone Number}}": "+1-234-567-8910",
"{{Client Service Working Hours}}": "Monday to Friday, 9 AM to 6 PM",
"{{Close}}": "Close",
"{{Close Account}}": "To close your account, contact support or visit your nearest branch.",
"{{Close Card}}": "Please call customer service to close your card.",
"{{Close Profile}}": "Go to account settings to close your profile.",
"{{Company}}": "MyBank Inc.",
"{{Company App}}": "MyBank Mobile",
"{{Company App Name}}": "MyBank Mobile",
"{{Company App Store}}": "Available on App Store",
"{{Company App Store/Google Play Store}}": "Download from App Store or Google Play",
"{{Company Branches}}": "Visit any of our 500+ branches nationwide",
"{{Company Email Address}}": "support@mybank.com",
"{{Company Industry}}": "Banking and Financial Services",
"{{Company Location}}": "New York, NY",
"{{Company Mobile App}}": "MyBank Mobile App",
"{{Company Mobile App Name}}": "MyBank Mobile",
"{{Company Name}}": "MyBank Inc.",
"{{Company Phone Number}}": "+1-800-555-1234",
"{{Company Play Store}}": "Available on Google Play Store",
"{{Company Store Locations}}": "www.mybank.com/branches",
"{{Company URL}}": "www.mybank.com",
"{{Company Website}}": "www.mybank.com",
"{{Company Website URL}}": "www.mybank.com",
"{{Company name}}": "MyBank Inc.",
"{{Confirm}}": "Confirm",
"{{Confirm Cancellation}}": "Please confirm your cancellation by clicking 'Confirm'.",
"{{Confirmation Method}}": "Email or SMS Verification",
"{{Contact}}": "Contact Us",
"{{Contact Amex Customer Support}}": "Call +1-800-528-4800 for American Express support.",
"{{Contact Channel}}": "Phone, Email, Live Chat",
"{{Contact Customer Support}}": "Reach our customer support team via phone or email.",
"{{Contact Details}}": "Phone: +1-800-555-1234, Email: support@mybank.com",
"{{Contact Email}}": "support@mybank.com",
"{{Contact Form}}": "www.mybank.com/contact",
"{{Contact Information}}": "Phone, Email, and Address of the company",
"{{Contact Local Banks or Credit Unions}}": "Search for local banks or credit unions in your area.",
"{{Contact Method}}": "Email, Phone, Chat",
"{{Contact Name}}": "Customer Service",
"{{Contact Number}}": "+1-800-555-1234",
"{{Contact Option}}": "Choose between Chat, Call, or Email",
"{{Contact Page}}": "www.mybank.com/contact",
"{{Contact Phone Number}}": "+1-800-555-1234",
"{{Contact Preference}}": "Choose your preferred method of contact",
"{{Contact Support Phone Number}}": "+1-800-555-1234",
"{{Contact Time}}": "Within 1 business day",
"{{Contact Us}}": "www.mybank.com/contact",
"{{Contact Visa Customer Support}}": "Call +1-800-VISA-911 for assistance.",
"{{Contact our Mortgage Department}}": "mortgage@mybank.com or +1-800-555-4567",
"{{Contact your Bank}}": "Contact your bank’s customer service department",
"{{Contact your Bank's Customer Service}}": "Call or email your bank's support team",
"{{Contact your Bank's Customer Service Department}}": "Available at +1-800-555-1234",
"{{Contact your Card Provider}}": "Reach out to your card provider's support team",
"{{Contact your bank}}": "Call or email your bank for assistance",
"{{Contact your credit card issuer}}": "Visit the official website or call support",
"{{Continue}}": "Continue",
"{{Convenience Stores}}": "Available at major convenience stores nationwide",
"{{Create Account}}": "Sign up to create a new account",
"{{Create New Account}}": "Register a new account at www.mybank.com/signup",
"{{Create Password}}": "Create a secure password",
"{{Create a New Password}}": "Set up your new password using the link sent",
"{{Credit Card}}": "Credit Card",
"{{Credit Card Account}}": "Your linked credit card account",
"{{Credit Card Activation}}": "Activate your credit card online or via phone",
"{{Credit Card Activation App}}": "Use the MyBank Mobile App to activate",
"{{Credit Card Activation Phone Number}}": "+1-800-555-2345",
"{{Credit Card App}}": "MyBank Credit App",
"{{Credit Card Balance}}": "$2,345.67",
"{{Credit Card Balances}}": "Check current and available balances",
"{{Credit Card Company}}": "MyBank Credit Services",
"{{Credit Card Company Website}}": "www.mybankcredit.com",
"{{Credit Card Company's Customer Support Phone Number}}": "+1-800-555-2345",
"{{Credit Card Company's Website URL}}": "www.mybankcredit.com",
"{{Credit Card Customer Service}}": "Credit Card Customer Support",
"{{Credit Card Customer Service Number}}": "+1-800-555-2345",
"{{Credit Card Customer Service number}}": "+1-800-555-2345",
"{{Credit Card Customer Support}}": "Credit card help and assistance team",
"{{Credit Card Customer Support Line}}": "+1-800-555-2345",
"{{Credit Card Details}}": "Credit Card Details",
"{{Credit Card Features}}": "Credit Card Features",
"{{Credit Card Hotline Number}}": "+1-800-555-2345",
"{{Credit Card Information}}": "Credit Card Information",
"{{Credit Card Issuer Support Phone Number}}": "+1-800-555-2345",
"{{Credit Card Management}}": "Credit Card Management",
"{{Credit Card Number}}": "Credit Card Number",
"{{Credit Card Online Portal}}": "www.mybank.com/creditportal",
"{{Credit Card Phone Number}}": "Credit Card Phone Number",
"{{Credit Card Provider}}": "MyBank",
"{{Credit Card Provider Website URL}}": "www.mybank.com/creditcards",
"{{Credit Card Services}}": "Credit Card Services",
"{{Credit Card Statement}}": "Credit Card Statement",
"{{Credit Card Support}}": "Credit Card Support",
"{{Credit Card Support Phone Number}}": "+1-800-555-2345",
"{{Credit Card Support Team}}": "Credit Card Support Team",
"{{Credit Card Terms and Conditions}}": "Credit Card Terms and Conditions",
"{{Credit Card Website}}": "www.mybank.com/creditcards",
"{{Credit Card or Banking}}": "Credit Card or Banking",
"{{Credit Card's Official Website}}": "www.mybank.com/creditcards",
"{{Credit Cards}}": "Credit Cards",
"{{Credit Score}}": "Credit Score",
"{{Credit Union 1}}": "Credit Union 1",
"{{Credit Union 2}}": "Community Credit Union - www.ccu.org",
"{{Credit Union 3}}": "Federal Credit Union - www.fcu.org",
"{{Credit Union A}}": "First Credit Union",
"{{Credit Union B}}": "Secure Credit Union",
"{{Credit Union Name}}": "Neighborhood Credit Union",
"{{Credit card}}": "Credit Card",
"{{Credit/Debit}}": "Credit or Debit Card",
"{{Currency}}": "USD",
"{{Current Balance}}": "$1,234.56",
"{{Current Year}}": "2025",
"{{Custom Dates}}": "Select a date range manually",
"{{Customer Account}}": "Account linked to the customer profile",
"{{Customer ID}}": "CUST-20250410-789",
"{{Customer Name}}": "John Doe",
"{{Customer Service}}": "Our dedicated customer support team",
"{{Customer Service Center}}": "MyBank Service Center, Downtown Branch",
"{{Customer Service Chat}}": "Live chat with a support agent",
"{{Customer Service Department}}": "Customer Relations Department",
"{{Customer Service Email}}": "service@mybank.com",
"{{Customer Service Email Address}}": "service@mybank.com",
"{{Customer Service Hotline}}": "24/7 Hotline: +1-800-555-4321",
"{{Customer Service Hotline Number}}": "+1-800-555-4321",
"{{Customer Service Hours}}": "9 AM – 6 PM, Monday to Friday",
"{{Customer Service Phone Number}}": "+1-800-555-4321",
"{{Customer Service Response Time}}": "Typically within 24 hours",
"{{Customer Service Team}}": "MyBank Customer Experience Team",
"{{Customer Service Working Hours}}": "Monday to Friday, 9 AM – 6 PM",
"{{Customer Support}}": "MyBank Customer Support",
"{{Customer Support Channel}}": "Live Chat",
"{{Customer Support Channels}}": "Phone, Email, Chat",
"{{Customer Support Contact}}": "support@mybank.com",
"{{Customer Support Contact Method}}": "Email or Phone",
"{{Customer Support Department}}": "Customer Success Department",
"{{Customer Support Email}}": "support@mybank.com",
"{{Customer Support Email Address}}": "support@mybank.com",
"{{Customer Support End Time}}": "6 PM",
"{{Customer Support FAQ}}": "www.mybank.com/help",
"{{Customer Support Helpline}}": "+1-800-555-4321",
"{{Customer Support Hotline}}": "+1-800-555-4321",
"{{Customer Support Hours}}": "Mon-Fri, 9 AM – 6 PM",
"{{Customer Support Live Chat}}": "Chat with our team instantly",
"{{Customer Support Live Chat URL}}": "www.mybank.com/livechat",
"{{Customer Support Operating Hours}}": "9 AM – 6 PM, Weekdays",
"{{Customer Support Page}}": "www.mybank.com/support",
"{{Customer Support Phone Line}}": "+1-800-555-4321",
"{{Customer Support Phone Number}}": "+1-800-555-4321",
"{{Customer Support Response Time}}": "Within 1 business day",
"{{Customer Support Start Time}}": "9 AM",
"{{Customer Support Team}}": "MyBank Support Team",
"{{Customer Support Website}}": "www.mybank.com/support",
"{{Customer Support Website URL}}": "www.mybank.com/support",
"{{Customer Support Working Hours}}": "9 AM to 6 PM, Monday to Friday",
"{{Date}}": "April 10, 2025",
"{{Date Range}}": "April 1, 2025 – April 10, 2025",
"{{Date and Time}}": "April 10, 2025, 2:45 PM",
"{{Date and Time of Transfer}}": "April 9, 2025, 4:20 PM",
"{{Date and Time of the Transaction}}": "April 8, 2025, 11:00 AM",
"{{Date of Birth}}": "January 1, 1990",
"{{Date of the withdrawal}}": "April 5, 2025",
"{{Days of the Week}}": "Monday, Tuesday, Wednesday, Thursday, Friday",
"{{Deactivate}}": "Deactivate",
"{{Deactivate Account}}": "You can deactivate your account in profile settings.",
"{{Deactivate Card}}": "Call +1-800-555-4321 to deactivate your card.",
"{{Deactivate Profile}}": "Visit your settings page to deactivate your profile.",
"{{Debit Card Number}}": "**** **** **** 5678",
"{{Delete}}": "Delete",
"{{Delete Account}}": "Your account will be permanently deleted.",
"{{Delete Profile}}": "This will remove all your personal data.",
"{{Delete Transfer}}": "Are you sure you want to delete this transfer?",
"{{Description}}": "Brief detail of the transaction",
"{{Desired Username}}": "john_doe92",
"{{Destination Account Number}}": "123456789012",
"{{Destination Bank}}": "National Bank of Country",
"{{Disable Card}}": "Temporarily disable your card from the app",
"{{Discover}}": "Discover Financial Services",
"{{Dispute}}": "Report a transaction issue",
"{{Dispute Center}}": "www.mybank.com/disputes",
"{{Dispute Department}}": "MyBank Dispute Resolution Unit",
"{{Dispute Email Address}}": "disputes@mybank.com",
"{{Dispute Form}}": "www.mybank.com/dispute-form",
"{{Dispute Resolution}}": "Resolution within 10 business days",
"{{Dispute Resolution Department}}": "Dispute and Fraud Division",
"{{Dispute Resolution Team}}": "Specialized Dispute Handling Team",
"{{Dispute Timeframe}}": "Investigation completed within 10 business days",
"{{Domestic Transfer}}": "Transfer within the same country",
"{{Email}}": "john.doe@example.com",
"{{Email Address}}": "john.doe@example.com",
"{{Email Inbox or Spam Folder}}": "Check both inbox and spam/junk folder",
"{{Email Response Time}}": "Within 24–48 hours",
"{{Email Support}}": "Reach us at support@mybank.com",
"{{Email Support Address}}": "support@mybank.com",
"{{Email address registered with the account}}": "john.doe@example.com",
"{{Emergency Helpline Number}}": "+1-800-555-9999",
"{{Emergency Hotline}}": "+1-800-555-9999",
"{{Employment History}}": "Record of your past employers",
"{{Evaluate alternatives}}": "Compare options before proceeding",
"{{Expiration Date}}": "Expiration Date",
"{{Expiry Date}}": "Expiry Date",
"{{Explain the Situation}}": "Provide a detailed explanation of the issue",
"{{FAQ and Help Center}}": "www.mybank.com/help",
"{{FAQs}}": "www.mybank.com/faqs",
"{{FAQs and Help Center}}": "www.mybank.com/help-center",
"{{Face ID}}": "Enable Face ID from your mobile app settings",
"{{Facebook}}": "facebook.com/mybankofficial",
"{{Fee Amount}}": "$15.00",
"{{Fee Information}}": "www.mybank.com/fees",
"{{Fee Range}}": "$5 – $50 depending on the service",
"{{Fee Summary}}": "Summary of fees applicable to your account",
"{{Fees}}": "Charges that apply to specific services",
"{{Fees and Charges}}": "See our complete list at www.mybank.com/fees",
"{{Fees and Rates}}": "Current rates and associated fees available online",
"{{Financial Advisor}}": "Your assigned financial advisor is Lisa Thompson",
"{{Financial Advisors}}": "Certified financial advisors available by appointment",
"{{Financial Assistance Programs}}": "www.mybank.com/assistance-programs",
"{{Financial Counseling Service}}": "We provide free financial counseling upon request",
"{{Financial Information}}": "Includes your income, expenses, and credit profile",
"{{Financial Institution}}": "MyBank, N.A.",
"{{Financial Services Department}}": "Located at the Main Branch, Floor 3",
"{{Financial Services Email Address}}": "financial@mybank.com",
"{{Financial Services Phone Number}}": "+1-800-555-9876",
"{{Find ATM}}": "www.mybank.com/find-atm",
"{{Find a Branch}}": "www.mybank.com/branches",
"{{Find an ATM}}": "Locate nearby ATMs using our app or website",
"{{Finish}}": "Click 'Finish' to complete your application",
"{{First Name}}": "John",
"{{Follow Cancellation Procedure}}": "Visit www.mybank.com/cancel to proceed",
"{{Forgot Password}}": "Reset it at www.mybank.com/forgot-password",
"{{Four Digits of Social Security Number}}": "1234",
"{{Fraud Department}}": "Fraud Investigation Unit at MyBank",
"{{Fraud Department Email Address}}": "fraud@mybank.com",
"{{Fraud Department Phone Number}}": "+1-800-555-4444",
"{{Fraud Department Working Hours}}": "Mon–Fri, 8 AM – 6 PM",
"{{Fraud Hotline Number}}": "+1-800-555-4444",
"{{Freeze}}": "Temporarily disable account/card",
"{{Freeze Card}}": "You can freeze your card from the app",
"{{Friend's Name}}": "Alex Johnson",
"{{From Account}}": "Savings Account ****4321",
"{{Full Name}}": "John Michael Doe",
"{{Gas Stations}}": "Chevron, Shell, ExxonMobil, BP",
"{{Go to your Account Settings}}": "Navigate to Settings > Account",
"{{Google Maps}}": "maps.google.com",
"{{Google Play}}": "Available on Google Play",
"{{Google Play Store}}": "Google Play Store",
"{{Google Play Store Link}}": "play.google.com/store/apps/details?id=com.mybank",
"{{Google Play Store URL}}": "https://play.google.com/store/apps/details?id=com.mybank",
"{{Help}}": "Visit www.mybank.com/help for assistance",
"{{Help & Support}}": "www.mybank.com/help-support",
"{{Help Center}}": "www.mybank.com/help-center",
"{{Help Center URL}}": "https://www.mybank.com/help-center",
"{{Hire a Mortgage Broker}}": "We recommend MyHome Brokers Inc. for mortgage help",
"{{Home Address}}": "123 Main St, Springfield, IL 62704",
"{{Home Loan Assistance Team}}": "Reach them at mortgagehelp@mybank.com",
"{{Hotline Number}}": "+1-800-555-1000",
"{{IBAN}}": "GB33BUKB20201555555555",
"{{IVR Phone Number}}": "+1-800-555-4321",
"{{Identification}}": "Valid government-issued ID required",
"{{Identification Documents}}": "Driver’s License, Passport, or State ID",
"{{Identification Number}}": "A123456789",
"{{Identifying Information}}": "Includes name, DOB, SSN, and address",
"{{Income Information}}": "Monthly income and employment verification",
"{{Instagram}}": "instagram.com/mybankofficial",
"{{International Activation Phone Number}}": "+1-800-555-7890",
"{{International Activation Support Hours}}": "24/7 Availability",
"{{International Customer Support Phone Number}}": "+1-800-555-7890",
"{{International Support Phone Number}}": "+1-800-555-7890",
"{{International Transfer}}": "Send money globally with our SWIFT service",
"{{International Usage}}": "Card valid internationally with no FX fees",
"{{Invoices}}": "Access your invoices at www.mybank.com/invoices",
"{{Issuer Website}}": "www.mybank.com",
"{{Landlord's Account Number}}": "098765432123",
"{{Landlord's Name}}": "Sarah Wilson",
"{{Last 4 Digits of Credit Card}}": "6789",
"{{Last 4 Digits of SSN}}": "1234",
"{{Last Four Digits}}": "4321",
"{{Last Four Digits of Social Security Number}}": "4321",
"{{Last Month}}": "March 2025",
"{{Last Name}}": "Doe",
"{{LendIt.com}}": "www.lendit.com",
"{{Lender 1 Website}}": "www.lenderone.com",
"{{Lender 2 Website}}": "www.lendertwo.com",
"{{Lender Directories}}": "www.mortgagefinder.com/lenders",
"{{Lender's Phone Number}}": "+1-800-555-2211",
"{{Lender's Website URL}}": "https://www.trustedlender.com",
"{{Lending Company Website}}": "www.quickloans.com",
"{{Lending Platform 1}}": "LendItNow",
"{{Lending Platform 2}}": "FastLoaner",
"{{Lending Platforms}}": "LendItNow, FastLoaner, TrustLend",
"{{LendingPlatform.com}}": "www.lendingplatform.com",
"{{Live Chat}}": "Connect instantly at www.mybank.com/livechat",
"{{Live Chat Support}}": "Available via our website or mobile app",
"{{Live Chat Support Hours}}": "9 AM – 9 PM, 7 days a week",
"{{Live Chat Working Hours}}": "9 AM – 9 PM",
"{{Live Chat support}}": "Chat now with a MyBank agent",
"{{Loan}}": "Personal loan up to $50,000 available",
"{{Loan Account}}": "Loan Account ending in 1234",
"{{Loan Account Number}}": "LN-20250410-7890",
"{{Loan Agreement}}": "Signed electronically via DocuSign",
"{{Loan Agreement Date}}": "March 15, 2025",
"{{Loan Agreement Number}}": "AGRMNT-879234",
"{{Loan Agreement Review}}": "Reviewed and accepted on March 15, 2025",
"{{Loan Amount}}": "Loan Amount",
"{{Loan Application}}": "Loan Application",
"{{Loan Application ID}}": "Loan Application ID",
"{{Loan Application Number}}": "Loan Application Number",
"{{Loan Application Page}}": "Loan Application Page",
"{{Loan Application Processing Time}}": "Loan Application Processing Time",
"{{Loan Application Processing Timeframe}}": "Loan Application Processing Timeframe",
"{{Loan Application Reference}}": "Loan Application Reference",
"{{Loan Application Reference Number}}": "Loan Application Reference Number",
"{{Loan Application URL}}": "www.loanprovider.com/apply",
"{{Loan Assistance}}": "Loan Assistance",
"{{Loan Assistance Contact Information}}": "+1-234-567-8910",
"{{Loan Assistance Department}}": "Loan Assistance Department",
"{{Loan Assistance Email}}": "loan-support@loancompany.com",
"{{Loan Assistance Phone Number}}": "+1-234-567-8910",
"{{Loan Assistance Team}}": "Loan Assistance Team",
"{{Loan Branches}}": "Nearby Loan Branches",
"{{Loan Cancelation Department}}": "Loan Cancellation Department",
"{{Loan Cancellation}}": "Loan Cancellation",
"{{Loan Cancellation Department}}": "Loan Cancellation Department",
"{{Loan Cancellation Department Phone Number}}": "+1-234-567-8910",
"{{Loan Cancellation Department Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Loan Cancellation Email}}": "loan-cancel@loancompany.com",
"{{Loan Cancellation Email Address}}": "loan-cancel@loancompany.com",
"{{Loan Cancellation Phone Number}}": "+1-234-567-8910",
"{{Loan Cancellation Policy}}": "Loan Cancellation Policy",
"{{Loan Cancellation Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Loan Center}}": "Loan Center",
"{{Loan Company Name}}": "LoanCompany",
"{{Loan Comparison Website}}": "www.compareloans.com",
"{{Loan Confirmation Number}}": "Loan Confirmation Number",
"{{Loan Customer Service}}": "Loan Customer Service",
"{{Loan Customer Support}}": "Loan Customer Support",
"{{Loan Customer Support Department}}": "Loan Customer Support Department",
"{{Loan Customer Support Email Address}}": "support@loancompany.com",
"{{Loan Customer Support Phone Number}}": "+1-234-567-8910",
"{{Loan Customer Support Team}}": "Loan Customer Support Team",
"{{Loan Dashboard}}": "Loan Dashboard",
"{{Loan Decision Timeframe}}": "Loan Decision Timeframe",
"{{Loan Department}}": "Loan Department",
"{{Loan Department Email}}": "loan-dept@loancompany.com",
"{{Loan Department Email Address}}": "loan-dept@loancompany.com",
"{{Loan Department Phone Number}}": "+1-234-567-8910",
"{{Loan Department Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Loan Details}}": "Loan Details",
"{{Loan ID}}": "Loan ID",
"{{Loan Information}}": "Loan Information",
"{{Loan Management}}": "Loan Management",
"{{Loan Management Account}}": "Loan Management Account",
"{{Loan Marketplace Name}}": "Loan Marketplace",
"{{Loan Modification}}": "Loan Modification",
"{{Loan Number}}": "Loan Number",
"{{Loan Officer}}": "Loan Officer",
"{{Loan Officer Name}}": "Loan Officer Name",
"{{Loan Officer's Name}}": "Loan Officer's Name",
"{{Loan Payment}}": "Loan Payment",
"{{Loan Payment Helpline Number}}": "+1-234-567-8910",
"{{Loan Payment History}}": "Loan Payment History",
"{{Loan Payment Portal}}": "www.loancompany.com/payment",
"{{Loan Payment Support Contact}}": "loan-payments@loancompany.com",
"{{Loan Payments}}": "Loan Payments",
"{{Loan Processing Time}}": "Loan Processing Time",
"{{Loan Processing Timeframe}}": "Loan Processing Timeframe",
"{{Loan Products}}": "Loan Products",
"{{Loan Provider}}": "Loan Provider",
"{{Loan Provider Phone Number}}": "+1-234-567-8910",
"{{Loan Provider Website URL}}": "www.loancompany.com",
"{{Loan Reference Number}}": "Loan Reference Number",
"{{Loan Repayment Options}}": "Loan Repayment Options",
"{{Loan Repayment Plan}}": "Loan Repayment Plan",
"{{Loan Restructuring Department}}": "Loan Restructuring Department",
"{{Loan Section}}": "Loan Section",
"{{Loan Service Department}}": "Loan Service Department",
"{{Loan Services}}": "Loan Services",
"{{Loan Services Department}}": "Loan Services Department",
"{{Loan Services Email Address}}": "services@loancompany.com",
"{{Loan Services Phone Number}}": "+1-234-567-8910",
"{{Loan Start Date}}": "Loan Start Date",
"{{Loan Support Contact Number}}": "+1-234-567-8910",
"{{Loan Support Department}}": "Loan Support Department",
"{{Loan Support Email}}": "loan-support@loancompany.com",
"{{Loan Support Email Address}}": "loan-support@loancompany.com",
"{{Loan Support Hours}}": "Mon-Fri, 9am to 6pm",
"{{Loan Support Phone Number}}": "+1-234-567-8910",
"{{Loan Support Team}}": "Loan Support Team",
"{{Loan Support Website}}": "www.loancompany.com/support",
"{{Loan Support Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Loan Term}}": "Loan Term",
"{{Loan cancellation department}}": "Loan Cancellation Department",
"{{LoanCompany.com}}": "www.loancompany.com",
"{{LoanWebsite.com}}": "www.loancompany.com",
"{{Loans}}": "Loans",
"{{Loans and Payments}}": "Loans and Payments",
"{{Local Bank 1}}": "Local Bank 1",
"{{Local Bank 2}}": "Local Bank 2",
"{{Local Bank 3}}": "Local Bank 3",
"{{Local Branches}}": "Nearby Branches",
"{{Local Mortgage Brokerage}}": "Local Mortgage Brokerage",
"{{Location}}": "Location",
"{{Locations}}": "Locations",
"{{Lock Card}}": "Lock Card",
"{{Lock/Block}}": "Lock or Block",
"{{Lock/Block Card}}": "Lock or Block Card",
"{{Login}}": "Login",
"{{Login Credentials}}": "Login Credentials",
"{{Login Page}}": "www.loancompany.com/login",
"{{Lost Card Phone Number}}": "+1-234-567-8910",
"{{Lost or Stolen Card Hotline}}": "+1-234-567-8910",
"{{Main Branch Address}}": "123 Main St, Springfield, IL 62704",
"{{Manage Account}}": "Manage Account",
"{{Manage Accounts}}": "Manage Accounts",
"{{Manage Card}}": "Manage Card",
"{{Manage Cards}}": "Manage Cards",
"{{Manage Loan}}": "Manage Loan",
"{{Manage My Account}}": "Manage My Account",
"{{Manage My Accounts}}": "Manage My Accounts",
"{{Manage Payments}}": "Manage Payments",
"{{Manage Transfers}}": "Manage Transfers",
"{{Manage Your Account}}": "Manage Your Account",
"{{Manage Your Cards}}": "Manage Your Cards",
"{{Map App}}": "Maps App",
"{{Map Website}}": "www.loancompany.com/maps",
"{{Maps}}": "Maps",
"{{Maps App}}": "Maps App",
"{{Maps Website}}": "www.loancompany.com/maps",
"{{Maximum Annual Fee}}": "Maximum Annual Fee",
"{{Minimum Annual Fee}}": "Minimum Annual Fee",
"{{Mobile App}}": "Loan Mobile App",
"{{Mobile App Name}}": "Loan Mobile App",
"{{Mobile Banking}}": "Mobile Banking",
"{{Mobile Banking App}}": "Mobile Banking App",
"{{Mobile Banking App Name}}": "Loan Mobile Banking App",
"{{Monthly Account Fee}}": "Monthly Account Fee",
"{{Monthly Statements}}": "Monthly Statements",
"{{Mortgage}}": "Mortgage",
"{{Mortgage Account}}": "Mortgage Account",
"{{Mortgage Account Dashboard}}": "Mortgage Account Dashboard",
"{{Mortgage Account Number}}": "Mortgage Account Number",
"{{Mortgage Account Portal}}": "www.loancompany.com/mortgage",
"{{Mortgage Advisor}}": "Mortgage Advisor",
"{{Mortgage Agreement}}": "Mortgage Agreement",
"{{Mortgage Application}}": "Mortgage Application",
"{{Mortgage Application Form}}": "Mortgage Application Form",
"{{Mortgage Application URL}}": "www.loancompany.com/mortgage/apply",
"{{Mortgage Assistance}}": "Mortgage Assistance",
"{{Mortgage Assistance Department}}": "Mortgage Assistance Department",
"{{Mortgage Assistance Email}}": "mortgage-help@loancompany.com",
"{{Mortgage Assistance Email Address}}": "mortgage-help@loancompany.com",
"{{Mortgage Assistance Phone Number}}": "+1-234-567-8910",
"{{Mortgage Assistance Team}}": "Mortgage Assistance Team",
"{{Mortgage Assistance Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Mortgage Bank}}": "Mortgage Bank",
"{{Mortgage Broker 1}}": "Mortgage Broker 1",
"{{Mortgage Broker 2}}": "Mortgage Broker 2",
"{{Mortgage Broker 3}}": "Mortgage Broker 3",
"{{Mortgage Broker Name}}": "Mortgage Broker Name",
"{{Mortgage Cancelation}}": "Mortgage Cancellation",
"{{Mortgage Cancelation Department}}": "Mortgage Cancellation Department",
"{{Mortgage Cancellation}}": "Mortgage Cancellation",
"{{Mortgage Cancellation Department}}": "Mortgage Cancellation Department",
"{{Mortgage Cancellation Department Email Address}}": "mortgage-cancel@loancompany.com",
"{{Mortgage Cancellation Department Phone Number}}": "+1-234-567-8910",
"{{Mortgage Cancellation Department Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Mortgage Cancellation Email}}": "mortgage-cancel@loancompany.com",
"{{Mortgage Cancellation Email Address}}": "mortgage-cancel@loancompany.com",
"{{Mortgage Cancellation Page}}": "www.loancompany.com/mortgage/cancel",
"{{Mortgage Cancellation Phone Number}}": "+1-234-567-8910",
"{{Mortgage Cancellation Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Mortgage Company}}": "Mortgage Company",
"{{Mortgage Comparison Websites}}": "www.comparemortgages.com",
"{{Mortgage Contact Number}}": "+1-234-567-8910",
"{{Mortgage Customer Service}}": "Mortgage Customer Service",
"{{Mortgage Customer Service Department}}": "Mortgage Customer Service Department",
"{{Mortgage Customer Service Email}}": "mortgage-support@loancompany.com",
"{{Mortgage Customer Service Phone Number}}": "+1-234-567-8910",
"{{Mortgage Customer Service Team}}": "Mortgage Customer Service Team",
"{{Mortgage Customer Support}}": "Mortgage Customer Support",
"{{Mortgage Customer Support Hours}}": "Mon-Fri, 9am to 6pm",
"{{Mortgage Customer Support Team}}": "Mortgage Customer Support Team",
"{{Mortgage Dashboard}}": "Mortgage Dashboard",
"{{Mortgage Department}}": "Mortgage Department",
"{{Mortgage Department Contact Number}}": "+1-234-567-8910",
"{{Mortgage Department Email}}": "mortgage@loancompany.com",
"{{Mortgage Department Email Address}}": "mortgage@loancompany.com",
"{{Mortgage Department Phone Number}}": "+1-234-567-8910",
"{{Mortgage Department Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Mortgage Email Address}}": "mortgage@loancompany.com",
"{{Mortgage Helpdesk}}": "Mortgage Helpdesk",
"{{Mortgage Helpline}}": "Mortgage Helpline",
"{{Mortgage Helpline Number}}": "+1-234-567-8910",
"{{Mortgage Lender}}": "Mortgage Lender",
"{{Mortgage Lender Name}}": "Mortgage Lender Name",
"{{Mortgage Lender Phone Number}}": "+1-234-567-8910",
"{{Mortgage Lender Website URL}}": "www.mortgagelender.com",
"{{Mortgage Lenders}}": "Mortgage Lenders",
"{{Mortgage Lending Company}}": "Mortgage Lending Company",
"{{Mortgage Number}}": "Mortgage Number",
"{{Mortgage Payment}}": "Mortgage Payment",
"{{Mortgage Payment Portal}}": "www.loancompany.com/mortgage/payment",
"{{Mortgage Payment Support}}": "mortgage-payments@loancompany.com",
"{{Mortgage Payments}}": "Mortgage Payments",
"{{Mortgage Phone Number}}": "+1-234-567-8910",
"{{Mortgage Portal}}": "Mortgage Portal",
"{{Mortgage Provider}}": "Mortgage Provider",
"{{Mortgage Provider Customer Support}}": "Mortgage Provider Customer Support",
"{{Mortgage Provider Name}}": "Mortgage Provider Name",
"{{Mortgage Provider Phone Number}}": "+1-234-567-8910",
"{{Mortgage Provider Website}}": "www.mortgageprovider.com",
"{{Mortgage Provider's}}": "Mortgage Provider's",
"{{Mortgage Provider's Customer Support}}": "Mortgage Provider's Customer Support",
"{{Mortgage Provider's Website}}": "www.mortgageprovider.com",
"{{Mortgage Reference Number}}": "Mortgage Reference Number",
"{{Mortgage Refinance}}": "Mortgage Refinance",
"{{Mortgage Refinancing Department}}": "Mortgage Refinancing Department",
"{{Mortgage Refinancing Program}}": "Mortgage Refinancing Program",
"{{Mortgage Representative's Email}}": "mortgage-rep@provider.com",
"{{Mortgage Service}}": "Mortgage Service",
"{{Mortgage Service Department}}": "Mortgage Service Department",
"{{Mortgage Service Phone Number}}": "+1-234-567-8910",
"{{Mortgage Service Provider}}": "Mortgage Service Provider",
"{{Mortgage Service Team}}": "Mortgage Service Team",
"{{Mortgage Services}}": "Mortgage Services",
"{{Mortgage Services Department}}": "Mortgage Services Department",
"{{Mortgage Services Email}}": "mortgage-services@provider.com",
"{{Mortgage Services Phone Number}}": "+1-234-567-8910",
"{{Mortgage Services Team}}": "Mortgage Services Team",
"{{Mortgage Servicing Department}}": "Mortgage Servicing Department",
"{{Mortgage Specialist}}": "Mortgage Specialist",
"{{Mortgage Specialist Team}}": "Mortgage Specialist Team",
"{{Mortgage Specialists}}": "Mortgage Specialists",
"{{Mortgage Support}}": "Mortgage Support",
"{{Mortgage Support Email}}": "mortgage-support@provider.com",
"{{Mortgage Support Email Address}}": "mortgage-support@provider.com",
"{{Mortgage Support Page}}": "www.mybank.com/mortgage-support",
"{{Mortgage Support Phone Number}}": "+1-234-567-8910",
"{{Mortgage Support Team}}": "Mortgage Support Team",
"{{Mortgage Support Website URL}}": "www.mybank.com/mortgage-support",
"{{Mortgage Support Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Mortgage Team}}": "Mortgage Team",
"{{Mortgage Website URL}}": "www.mybank.com/mortgage",
"{{Mortgage section}}": "Mortgage Section",
"{{My Account}}": "My Account",
"{{My Cards}}": "My Cards",
"{{My Fees}}": "My Fees",
"{{My Loans}}": "My Loans",
"{{My Mortgage Payments}}": "My Mortgage Payments",
"{{My Orders}}": "My Orders",
"{{My Payments}}": "My Payments",
"{{My Profile}}": "My Profile",
"{{My Transactions}}": "My Transactions",
"{{MyBank}}": "MyBank",
"{{Name}}": "Name",
"{{Name associated with the account}}": "Name associated with the account",
"{{Name on Card}}": "Name on Card",
"{{Name on the Card}}": "Name on the Card",
"{{Name on the Loan Account}}": "Name on the Loan Account",
"{{Name on the Mortgage}}": "Name on the Mortgage",
"{{Name on the Mortgage Account}}": "Name on the Mortgage Account",
"{{Nearest Branch Location}}": "Nearest Branch Location",
"{{Next}}": "Next",
"{{OTP}}": "OTP",
"{{One-Time Passcode}}": "One-Time Passcode",
"{{One-Time Password}}": "One-Time Password",
"{{One-Time Password (OTP)}}": "One-Time Password (OTP)",
"{{One-time Password}}": "One-time Password",
"{{Online Account}}": "Online Account",
"{{Online Banking}}": "Online Banking",
"{{Online Banking Account}}": "Online Banking Account",
"{{Online Banking Password}}": "Online Banking Password",
"{{Online Banking Platform}}": "Online Banking Platform",
"{{Online Banking Portal}}": "Online Banking Portal",
"{{Online Banking Portal URL}}": "www.mybank.com/online-banking",
"{{Online Card Services}}": "Online Card Services",
"{{Online Chat Support}}": "Online Chat Support",
"{{Online Contact Form}}": "Online Contact Form",
"{{Online Lender 1}}": "LendPro",
"{{Online Lender 2}}": "QuickLoans",
"{{Online Lender 3}}": "FlexiFinance",
"{{Online Lender Name}}": "Online Lender Name",
"{{Online Lending Platform 1}}": "LendPro Platform",
"{{Online Lending Platform 2}}": "QuickLoans Platform",
"{{Online Mortgage Platform 1}}": "MortgageEasy",
"{{Online Mortgage Platform 2}}": "HomeLoansNow",
"{{Opening Hours}}": "Mon-Fri, 9am to 6pm",
"{{Order History}}": "Order History",
"{{Order Number}}": "Order Number",
"{{Overdraft Fee}}": "Overdraft Fee",
"{{P2P Platform 1}}": "PeerPay",
"{{P2P Platform 2}}": "ConnectFunds",
"{{PIN}}": "PIN",
"{{PIN Number}}": "PIN Number",
"{{Partner Banks}}": "Partner Banks",
"{{Password}}": "Password",
"{{Password Management}}": "Password Management",
"{{Password Recovery}}": "Password Recovery",
"{{Password Reset}}": "Password Reset",
"{{Password Settings}}": "Password Settings",
"{{Password Setup}}": "Password Setup",
"{{Payment}}": "Payment",
"{{Payment & Billing}}": "Payment & Billing",
"{{Payment Center}}": "Payment Center",
"{{Payment Date}}": "Payment Date",
"{{Payment Details}}": "Payment Details",
"{{Payment History}}": "Payment History",
"{{Payment Information}}": "Payment Information",
"{{Payment Method}}": "Payment Method",
"{{Payment Period}}": "Payment Period",
"{{Payment Records}}": "Payment Records",
"{{Payment Section}}": "Payment Section",
"{{Payment Summary}}": "Payment Summary",
"{{Payment\"}}": "Payment",
"{{Payments}}": "Payments",
"{{Peer-to-Peer Lender 1}}": "PeerFund",
"{{Peer-to-Peer Lender 2}}": "LendCircle",
"{{Peer-to-Peer Platform 1}}": "PeerFund Platform",
"{{Peer-to-Peer Platform 2}}": "LendCircle Platform",
"{{Peer-to-Peer Transfer}}": "Peer-to-Peer Transfer",
"{{PeerLending.com}}": "www.peerlending.com",
"{{Personal Identification}}": "Personal Identification",
"{{Personal Identification Details}}": "Personal Identification Details",
"{{Personal Identification Documents}}": "Personal Identification Documents",
"{{Personal Identification Information}}": "Personal Identification Information",
"{{Personal Information}}": "Personal Information",
"{{Phone}}": "Phone",
"{{Phone Banking Number}}": "+1-234-567-8910",
"{{Phone Call}}": "Phone Call",
"{{Phone Number}}": "+1-234-567-8910",
"{{Phone Support}}": "Phone Support",
"{{Platform 1}}": "Platform 1",
"{{Platform 2}}": "Platform 2",
"{{Preferences}}": "Preferences",
"{{Preferred Contact Method}}": "Preferred Contact Method",
"{{Pricing}}": "Pricing",
"{{Pricing and Fees}}": "Pricing and Fees",
"{{Pricing and Terms}}": "Pricing and Terms",
"{{Privacy}}": "Privacy",
"{{Privacy Policy}}": "Privacy Policy",
"{{Processing Time}}": "Processing Time",
"{{Product Name}}": "Product Name",
"{{Product/Service}}": "Product/Service",
"{{Profile}}": "Profile",
"{{Profile Information}}": "Profile Information",
"{{Profile Management}}": "Profile Management",
"{{Profile Name}}": "Profile Name",
"{{Profile Settings}}": "Profile Settings",
"{{Profile Username}}": "Profile Username",
"{{Proof of Address}}": "Proof of Address",
"{{Proof of Identification}}": "Proof of Identification",
"{{Proof of Identity}}": "Proof of Identity",
"{{Proof of Property Ownership}}": "Proof of Property Ownership",
"{{Proof of Residence}}": "Proof of Residence",
"{{Property Address}}": "Property Address",
"{{Provide Required Information}}": "Provide Required Information",
"{{Provide the Necessary Information}}": "Provide the Necessary Information",
"{{Reason}}": "Reason",
"{{Reason for Cancellation}}": "Reason for Cancellation",
"{{Recent Transactions}}": "Recent Transactions",
"{{Recipient Account Details}}": "Recipient Account Details",
"{{Recipient Account Number}}": "Recipient Account Number",
"{{Recipient Name}}": "Recipient Name",
"{{Recipient's Account Details}}": "Recipient's Account Details",
"{{Recipient's Account Information}}": "Recipient's Account Information",
"{{Recipient's Account Name}}": "Recipient's Account Name",
"{{Recipient's Account Number}}": "Recipient's Account Number",
"{{Recipient's Account Number or Name}}": "Recipient's Account Number or Name",
"{{Recipient's Bank Name}}": "Recipient's Bank Name",
"{{Recipient's Name}}": "Recipient's Name",
"{{Reference Number}}": "Reference Number",
"{{Reference or Description for the Payment}}": "Reference or Description for the Payment",
"{{Refinance Department}}": "Refinance Department",
"{{Refund}}": "Refund",
"{{Registered Email Address}}": "user@example.com",
"{{Registration Information}}": "Registration Information",
"{{Rent Amount}}": "Rent Amount",
"{{Report Lost/Stolen}}": "Report Lost/Stolen",
"{{Report Lost/Stolen Card}}": "Report Lost/Stolen Card",
"{{Report a Problem}}": "Report a Problem",
"{{Report the Lost Card}}": "Report the Lost Card",
"{{Request Cancellation}}": "Request Cancellation",
"{{Request Card Cancellation}}": "Request Card Cancellation",
"{{Request Card Closure}}": "Request Card Closure",
"{{Request Loan Cancellation}}": "Request Loan Cancellation",
"{{Request a Replacement Card}}": "Request a Replacement Card",
"{{Research online}}": "Research online",
"{{Reset}}": "Reset",
"{{Reset Password}}": "Reset Password",
"{{Residential Address}}": "Residential Address",
"{{Response Time}}": "Response Time",
"{{Response Timeframe}}": "Response Timeframe",
"{{Reverse}}": "Reverse",
"{{Revoke}}": "Revoke",
"{{Routing Number}}": "Routing Number",
"{{SWIFT/BIC Code}}": "SWIFT/BIC Code",
"{{Salutation}}": "Salutation",
"{{Save}}": "Save",
"{{Save Changes}}": "Save Changes",
"{{Savings Account}}": "Savings Account",
"{{Secure Code}}": "Secure Code",
"{{Security}}": "Security",
"{{ecurity & Privacy}}": "Security & Privacy",
"{{Security Code}}": "Security Code",
"{{Security Method}}": "Security Method",
"{{Security Question}}": "Security Question",
"{{Security Settings}}": "Security Settings",
"{{Self-Service Portal}}": "Self-Service Portal",
"{{Send Money}}": "Send Money",
"{{Sender's Account Number}}": "Sender's Account Number",
"{{Sender's Information}}": "Sender's Information",
"{{Sender's Name}}": "Sender's Name",
"{{Sending Account Number}}": "Sending Account Number",
"{{Service Fee}}": "Service Fee",
"{{Service Fees}}": "Service Fees",
"{{Set New Password}}": "Set New Password",
"{{Set Password}}": "Set Password",
"{{Set Up Password}}": "Set Up Password",
"{{Set up Password}}": "Set up Password",
"{{Settings}}": "Settings",
"{{Shipping Address}}": "Shipping Address",
"{{Shopping Malls}}": "Shopping Malls",
"{{Sign In}}": "Sign In",
"{{Sign Up}}": "Sign Up",
"{{Sign-in}}": "Sign-in",
"{{Social Media}}": "Social Media",
"{{Social Media Channel}}": "Social Media Channel",
"{{Social Media Channels}}": "Social Media Channels",
"{{Social Media Handle}}": "Social Media Handle",
"{{Social Media Handles}}": "Social Media Handles",
"{{Social Media Platform}}": "Social Media Platform",
"{{Social Media Platforms}}": "Social Media Platforms",
"{{Social Media Profile Name}}": "Social Media Profile Name",
"{{Social Media Support}}": "Social Media Support",
"{{Social Security Number}}": "Social Security Number",
"{{Speak with an Agent}}": "Speak with an Agent",
"{{Specific Inquiry}}": "Specific Inquiry",
"{{Specific Issue}}": "Specific Issue",
"{{Standard Response Time}}": "Standard Response Time",
"{{Statement}}": "Statement",
"{{Statements}}": "Statements",
"{{Stop}}": "Stop",
"{{Submit}}": "Submit",
"{{Support}}": "Support",
"{{Support Center}}": "Support Center",
"{{Support Contact Information}}": "Support Contact Information",
"{{Support Email}}": "support@example.com",
"{{Support Email Address}}": "support@example.com",
"{{Support Hours}}": "Mon-Fri, 9am to 6pm",
"{{Support Phone Number}}": "+1-234-567-8910",
"{{Support Team}}": "Support Team",
"{{Support Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Suspend Card}}": "Suspend Card",
"{{Talk to a Human}}": "Talk to a Human",
"{{Talk to an Agent}}": "Talk to an Agent",
"{{Telephone Banking Number}}": "+1-234-567-8910",
"{{Temporarily Disable Card}}": "Temporarily Disable Card",
"{{Temporary Freeze}}": "Temporary Freeze",
"{{Terms and Conditions}}": "Terms and Conditions",
"{{Terms of Service}}": "Terms of Service",
"{{Third-Party ATM Locator Website 1}}": "www.thirdparty.com/atm-locator",
"{{Third-Party ATM Locator Website 2}}": "www.otheratmfinder.com",
"{{Third-party ATM Locator Website}}": "www.thirdparty.com/atm",
"{{Third-party Mapping App}}": "Google Maps",
"{{Time}}": "Time",
"{{Time Period}}": "Time Period",
"{{Timezone}}": "Timezone",
"{{To Account}}": "To Account",
"{{Touch ID}}": "Touch ID",
"{{Transaction}}": "Transaction",
"{{Transaction Amount}}": "Transaction Amount",
"{{Transaction Date}}": "Transaction Date",
"{{Transaction Date and Time}}": "Transaction Date and Time",
"{{Transaction Details}}": "Transaction Details",
"{{Transaction Fee}}": "Transaction Fee",
"{{Transaction Fees}}": "Transaction Fees",
"{{Transaction History}}": "Transaction History",
"{{Transaction ID}}": "Transaction ID",
"{{Transaction Number}}": "Transaction Number",
"{{Transaction Pin}}": "Transaction PIN",
"{{Transaction Records}}": "Transaction Records",
"{{Transaction Reference Number}}": "Transaction Reference Number",
"{{Transaction Summary}}": "Transaction Summary",
"{{Transaction Type}}": "Transaction Type",
"{{Transactions}}": "Transactions",
"{{Transfer}}": "Transfer",
"{{Transfer Amount}}": "Transfer Amount",
"{{Transfer Date}}": "Transfer Date",
"{{Transfer Details}}": "Transfer Details",
"{{Transfer Funds}}": "Transfer Funds",
"{{Transfer History}}": "Transfer History",
"{{Transfer ID}}": "Transfer ID",
"{{Transfer ID or Reference Number}}": "Transfer ID or Reference Number",
"{{Transfer ID/Reference Number}}": "Transfer ID/Reference Number",
"{{Transfer Identification Number}}": "Transfer Identification Number",
"{{Transfer Policy}}": "Transfer Policy",
"{{Transfer Reference Number}}": "Transfer Reference Number",
"{{Transfer section}}": "Transfer Section",
"{{Transfers}}": "Transfers",
"{{Travel Dates}}": "Travel Dates",
"{{Twitter}}": "Twitter",
"{{Two-Factor Authentication}}": "Two-Factor Authentication",
"{{Type of Mortgage}}": "Type of Mortgage",
"{{URL Website}}": "www.companywebsite.com",
"{{Undo}}": "Undo",
"{{Unique Username}}": "Unique Username",
"{{Unlock Card}}": "Unlock Card",
"{{Update}}": "Update",
"{{Update Password}}": "Update Password",
"{{User Account Details}}": "User Account Details",
"{{User Account Username}}": "User Account Username",
"{{User ID}}": "User ID",
"{{User Name}}": "User Name",
"{{Username}}": "Username",
"{{Username / Account ID}}": "Username / Account ID",
"{{Verification Code}}": "Verification Code",
"{{Verification Details}}": "Verification Details",
"{{Verification Information}}": "Verification Information",
"{{View Account Fees}}": "View Account Fees",
"{{View Balance}}": "View Balance",
"{{View Card Balance}}": "View Card Balance",
"{{View Current Balance}}": "View Current Balance",
"{{View Fees}}": "View Fees",
"{{View Loan Payments}}": "View Loan Payments",
"{{View Mortgage Payment}}": "View Mortgage Payment",
"{{View Mortgage Payment Summary}}": "View Mortgage Payment Summary",
"{{View Mortgage Payments}}": "View Mortgage Payments",
"{{View Payment History}}": "View Payment History",
"{{View Payments}}": "View Payments",
"{{View Recent Activity}}": "View Recent Activity",
"{{Visa}}": "Visa",
"{{Visa Card Activation}}": "Visa Card Activation",
"{{Visa Card Number}}": "Visa Card Number",
"{{Visa Customer Service}}": "Visa Customer Service",
"{{Visa Customer Service Contact Number}}": "+1-234-567-8910",
"{{Visa Customer Support}}": "Visa Customer Support",
"{{Visa Customer Support Number}}": "+1-234-567-8910",
"{{Visa Customer Support Phone Number}}": "+1-234-567-8910",
"{{Visa Website URL}}": "www.visa.com",
"{{Visa's official website}}": "www.visa.com",
"{{Visit our website}}": "www.companywebsite.com",
"{{Void}}": "Void",
"{{Website}}": "Website",
"{{Website Chat}}": "Website Chat",
"{{Website Chat Support URL}}": "www.companywebsite.com/livechat",
"{{Website Homepage}}": "www.companywebsite.com",
"{{Website Live Chat}}": "Website Live Chat",
"{{Website URL}}": "www.companywebsite.com",
"{{Wire Transfer}}": "Wire Transfer",
"{{Withdrawal Amount}}": "Withdrawal Amount",
"{{Working Hours}}": "Mon-Fri, 9am to 6pm",
"{{Yelp}}": "Yelp",
"{{Your Apartment Number or any other reference provided by your landlord}}": "Apartment Reference",
"{{Your Full Name}}": "Your Full Name",
"{{Your Name}}": "Your Name",
"{{ZIP Code}}": "ZIP Code",
"{{Zip Code}}": "ZIP Code",
"{{account email address}}": "account email address",
"{{account information}}": "account information",
"{{account number}}": "account number",
"{{additional details}}": "additional details",
"{{address}}": "address",
"{{amount}}": "amount",
"{{bank account}}": "bank account",
"{{bank account details}}": "bank account details",
"{{bank name}}": "bank name",
"{{bank's website}}": "www.bank.com",
"{{biometric data}}": "biometric data",
"{{card number}}": "card number",
"{{cardholder name}}": "cardholder name",
"{{company website}}": "www.companywebsite.com",
"{{company website URL}}": "www.companywebsite.com",
"{{companywebsite.com}}": "www.companywebsite.com",
"{{credit card number}}": "credit card number",
"{{customer support email}}": "support@example.com",
"{{customer support phone number}}": "+1-234-567-8910",
"{{customer support working hours}}": "Mon-Fri, 9am to 6pm",
"{{customer_service_email}}": "support@example.com",
"{{customer_service_phone}}": "+1-234-567-8910",
"{{date}}": "date",
"{{email}}": "email",
"{{email account}}": "email account",
"{{email address}}": "email address",
"{{expiration date}}": "expiration date",
"{{full name}}": "full name",
"{{last 3 months}}": "last 3 months",
"{{last four digits of your social security number}}": "last four digits of your SSN",
"{{loan account number}}": "loan account number",
"{{loan reference number}}": "loan reference number",
"{{loan section}}": "loan section",
"{{merchant name}}": "merchant name",
"{{mortgage account number}}": "mortgage account number",
"{{mortgage section}}": "mortgage section",
"{{my Amex Customer Service Hours}}": "24/7",
"{{my Amex Customer Service Phone Number}}": "+1-800-528-4800",
"{{name}}": "name",
"{{password}}": "password",
"{{pay stubs or tax returns}}": "pay stubs or tax returns",
"{{payment amount}}": "payment amount",
"{{payment date}}": "payment date",
"{{phone}}": "phone",
"{{phone number}}": "phone number",
"{{property address}}": "property address",
"{{reason}}": "reason",
"{{recipient's name}}": "recipient's name",
"{{registered email address}}": "registered email address",
"{{routing number}}": "routing number",
"{{security code}}": "security code",
"{{sender's name}}": "sender's name",
"{{social media account}}": "social media account",
"{{support@example.com}}": "support@example.com",
"{{time}}": "time",
"{{transaction ID}}": "transaction ID",
"{{transaction amount}}": "transaction amount",
"{{transaction date}}": "transaction date",
"{{transaction date/time}}": "transaction date/time",
"{{transaction details}}": "transaction details",
"{{transfer reference number}}": "transfer reference number",
"{{username}}": "username",
"{{valid ID}}": "valid ID",
"{{website}}": "website",
"{{website URL}}": "www.companywebsite.com",
"{{www.companywebsite.com}}": "www.companywebsite.com",
"{{www.example.com}}": "www.example.com",
"{{{{Credit Card}} Customer Service}}":"Credit Card Customer Service",
"{{ Loan Customer Support Department}}": "Loan Customer Support Department",
"{{Account}}":"Account",
"{{{{Credit Card}} Number}}":"Credit Card Number",
"{{{{Credit Card}}}}":"Credit Card",
"{{{{Credit Card}} Number}}":"Credit Card Number"}
